---
- name: System Hardening
  hosts: linux
  become: true
  collections:
    - Linux.Redhat8

  tasks:

    - name: Replace Maximum Authentication trie to 3 
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#MaxAuthTries=
      line: MaxAuthTries 3

    - name: Replace Maximum Sessions to 5 
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#MaxSessions=
      line: MaxSessions 5

    - name: Replace Compressions delay to no
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#Compression delayed
      line: Compression no

    - name: Set AllowAgentForwarding to no
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#AllowAgentForwarding=
      line: AllowAgentForwarding no

    - name:  Set PermitRootLogin to no
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^PermitRootLogin=
      line: PermitRootLogin no

    - name: Set ClientAliveInterval to 600 
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^ClientAliveInterval=
      line: ClientAliveInterval 600

    - name: Set AllowTcpForwarding to no
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#AllowTcpForwarding=
      line: 'AllowTcpForwarding no'

    - name: Replace PasswordAuthentication to no
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^PasswordAuthentication=
      line: PasswordAuthentication no

    - name: Comment out GSSAPIAuthentication
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^GSSAPIAuthentication=
      state: present
      line: '#GSSAPIAuthentication yes'

    - name: Comment out GSSAPICleanupCredentials 
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^GSSAPICleanupCredentials
      state: present
      line: '#GSSAPICleanupCredentials no'

    - name: Allow PubkeyAuthentication
      ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: ^#PubkeyAuthentication=
      line: PubkeyAuthentication yes

    - import_role:
        name: CISRHEL

    - name: Update the crypto policy to FUTURE. 
      ansible.builtin.shell:
        cmd: update-crypto-policies --set FUTURE

