### REQUIRED

# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: Linux

# The name of the collection. Has the same character restrictions as 'namespace'
name: Redhat8

# The version of the collection. Must be compatible with semantic versioning
version: 1.0.0

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
- Ansible Lockdown for CISRHEL and Manish Jani for ISMRHEL8


### OPTIONAL but strongly recommended

# A short summary description of the collection
description: This is a collection for Linux Red Hat 8 image. It includes CIS and ISM roles. CIS roles can be 
finetuned by amending the defaults/main.yml and exlude the controls which are not required. 

# The URL of the originating SCM repository
repository: http://github.com/ansible-lockdown

